apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker/docker-compose-resolved.yaml
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: ride-service
  name: ride-service
spec:
  ports:
    - name: "9990"
      port: 9990
      targetPort: 9990
  selector:
    io.kompose.service: ride-service
