services:
  pg-user:
    image: postgres
    hostname: ${PG_HOST}
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PG_USER: ${PG_USER}

    networks:
      - service-net

    volumes:
      - ./pg_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  user-service:
    image: sfuri/user-service:0.2.0
    ports:
      - ${SERVICE_PORT}:${SERVICE_PORT}
    environment:
      PORT: ${SERVICE_PORT}
      POSTGRES_HOST: ${PG_HOST}
    env_file: .env
    networks:
      - service-net

    depends_on:
      pg-user:
        condition: service_healthy

networks:
  service-net:
    external:
      true
