apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    scrape_configs:
      - job_name: 'rid-service'
        metrics_path: '/metrics'
        scrape_interval: 15s
        static_configs:
          - targets: ['ride-service:9990']

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ride-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ride-metrics
  template:
    metadata:
      labels:
        app: ride-metrics
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: prometheus-config
          mountPath: /etc/prometheus/prometheus.yml
          subPath: prometheus.yml
      volumes:
      - name: prometheus-config
        configMap:
          name: prometheus-config

