apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath -f docker/docker-compose-resolved.yaml
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: user-service
  name: user-service
spec:
  ports:
    - name: "11000"
      port: 11000
      targetPort: 11000
  selector:
    io.kompose.service: user-service
