/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.kotlin-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":utilities"))
    implementation("io.github.resilience4j:resilience4j-circuitbreaker:1.7.1")
}

application {
    // Define the main class for the application.
    mainClass = "org.example.app.AppKt"
}
