# Deploy configuration (replacement for simple .env file) services.
# While not sensitive stuff can be deployed in a simple `ConfigMap`,
# things like passwords and vehiclenames should be deployed through secrets.
#
# Note: even when using `Secret`, it is not a good practice to place
# the base64 encoded value directly in this file! We have made this
# for the sake of simplicity of this assignment.

apiVersion: v1
kind: ConfigMap
metadata:
  name: vehicle-service-config
data:
  POSTGRES_HOST: "pg-vehicle"
  SERVICE_PORT: "12000"
  DB_NAME: "vehicle-service"
  PG_vehicle: "postgres"

---

apiVersion: v1
kind: Secret
metadata:
  name: vehicle-service-secrets
type: Opaque
data: # data must be base64 encoded, here we've computed base64 encoding of "postgres"
  DB_vehicle: cG9zdGdyZXM=
  DB_PASSWORD: cG9zdGdyZXM=

