# Define and create volumes used by postgress in vehicle-service,
# it is mandatory to define a `PersistentVolume` service and its
# corresponding claim for actual permission granting.
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-vehicle-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath: # NOT SUITABLE FOR PRODUCTION, but good for minikube :)
    path: /data/postgres-vehicle

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-vehicle-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

