# Simple mapping of postgres and vehicle-service web server
# into their corresponding services.

apiVersion: v1
kind: Service
metadata:
  name: vehicle-service
spec:
  selector:
    app: vehicle-service
  ports:
    - port: 11000
      targetPort: 11000
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: pg-vehicle
spec:
  selector:
    app: pg-vehicle
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
