apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f kafka.yaml
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: zookeeper
  name: zookeeper
spec:
  ports:
    - protocol: TCP
      port: 2181
      targetPort: 2181
  selector:
    io.kompose.service: zookeeper
  type: ClusterIP
