apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehicle-service
spec:
  selector:
    matchLabels:
      app: vehicle-service
  template:
    metadata:
      labels:
        app: vehicle-service
    spec:
      containers:
        - name: vehicle-service
          image: matteoiorio/vehicle-service:2.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1926
---
apiVersion: v1
kind: Service
metadata:
  name: vehicle-service
spec:
  selector:
    app: vehicle-service
  ports:
    - port: 1926
