# Simple mapping of postgres and user-service web server
# into their corresponding services.

apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - port: 11000
      targetPort: 11000
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: pg-user
spec:
  selector:
    app: pg-user
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
