/*
 * This file was generated by the Gradle 'init' task.
 */

plugins { id("buildlogic.kotlin-application-conventions") }

dependencies {}

application {
    // Define the main class for the application.
    mainClass = "it.unibo.sap.ass02.MainKt"
}
