services:
  ride-service:
    image: sfuri/ride-service:0.2.0
    hostname: ride-service
    ports:
      - 9990:9990
    env_file:
      ../.env
    networks:
      service-net:

  ride-metrics:
    image: prom/prometheus
    depends_on:
      - ride-service
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
      service-net:

networks:
  service-net:
    external: true

