apiVersion: v1
kind: ConfigMap
metadata:
  name: ride-registry-config
data:
  POSTGRES_DB: ride-repo
  PG_USEAR: postgres
  DB_NAME: ride-repo
  DB_USER: postgres
  DB_PASSWORD: postgres
  PG_USER: postgres
  PG_HOST: pg-ride
  GATEWAY_HOST: api-gateway
  GATEWAY_PORT: 4001
  userPORT: 9991
---

apiVersion: v1
kind: Secret
metadata:
  name: ride-registry-secrets
type: Opaque
data:
  DB_USER: cG9zdGdyZXM=
  DB_PASSWORD: cG9zdGdyZXM=
