apiVersion: apps/v1
kind: Deployment
metadata:
  name: ride-repository
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ride-repository
  template:
    metadata:
      labels:
        app: ride-repository
    spec:
      containers:
      - name: ride-repository
        image: sfuri/ride-registry:0.1.3
        ports:
        - containerPort: 9991
        envFrom:
        - configMapRef:
            name: ride-registry-config
        - secretRef:
            name: ride-registry-secrets

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-ride
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pg-ride
  template:
    metadata:
      labels:
        app: pg-ride
    spec:
      containers:
      - name: postgres
        image: postgres
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: ride-registry-config
        - secretRef:
            name: ride-registry-secrets
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        resources:
          limits:
            memory: "256Mi"
          requests:
            memory: "128Mi"
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-ride-pvc

