apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-ride-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/postgres-ride

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-ride-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

