apiVersion: v1
kind: Service
metadata:
  name: ride-registry
spec:
  selector:
    app: ride-registry
  ports:
    - port: 9991
      targetPort: 9991
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: pg-ride
spec:
  selector:
    app: pg-ride
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP

